### ISSUE TITLE
Cannot read property 'body' of undefined

### ISSUE THREAD

**Issue by alikkane** [adonisjs/adonis-mail#28]
TypeError: Cannot read property 'body' of undefined
    at Request.post (/Users/mac/NickelIT/Projects/Adonis/project-aviscan/node_modules/@adonisjs/mail/src/Request/index.js:98:31)

**Comment by RomainLanz** [comment]
Hey @alikkane! 👋 

We cannot do much with this kind of issue, please share with us some code.

**Comment by thetutlage** [comment]
Closing since no response from the issue reporter and not actionable as well

**Comment by jsdecena** [comment]
I know this is already closed but I am getting this error as well. Here's the test case:

```
const Mail = use('Mail')

test('it can trigger the email for sending inquiry', async ({ assert }) => {

  Mail.fake()

  const user = await UserRepository.create({email: faker.internet.email(), password: 'secret'})
  const data = { user, content: 'hello world' }

  await UserRepository.sendEmail({ user, data })

  const recentEmail = Mail.pullRecent()

  assert.equal(recentEmail.message.to[0].address, data.user.email)
  assert.equal(recentEmail.message.to[0].to, Config.get('mail.defaultEmail'))

  Mail.restore()  
})
```

My `sendEmail()` method

```
...
    static sendEmail(data) {
        Mail.send('emails.inquire', data, (message) => {
            message
                .to(Config.get('mail.defaultEmail'))
                .from(data.user.email)
                .subject(Config.get('mail.defaultEmailSubject'))
        })
    }
```

This is the error:

```
 1. it can trigger the email for sending inquiry
  TypeError: Cannot read property 'message' of undefined
    at Callable.test [as _fn] (/Users/jsdecena/Code/multisys/dockerized/nbi-ws/test/unit/Users/user.spec.js:203:28)
```
