### ISSUE TITLE
[MailGun] GotError: options.body must be a ReadableStream, string or Buffer

### ISSUE THREAD

**Issue by RomainLanz** [adonisjs/adonis-mail#4]
**adonis-mail version**: `git#develop`
**Driver used**: `mailgun`
**Node.js version**: v6.4.0
**npm version**: v3.10.3

Hey !

I got an error from `got` when I try to send a email with the `mailgun` driver.

<details><summary>Exception</summary>
```
{ GotError: options.body must be a ReadableStream, string or Buffer
    at got (/Users/romainlanz/workspace/qualitas-helvetica.ch/node_modules/got/index.js:81:10)
    at Function.got.(anonymous function) [as post] (/Users/romainlanz/workspace/qualitas-helvetica.ch/node_modules/got/index.js:272:10)
    at MailGunTransport.send (/Users/romainlanz/workspace/qualitas-helvetica.ch/node_modules/adonis-mail-provider/src/Mail/Drivers/MailGun/transport.js:75:9)
    at Nodemailer.<anonymous> (/Users/romainlanz/workspace/qualitas-helvetica.ch/node_modules/nodemailer/lib/nodemailer.js:324:30)
    at Nodemailer._processPlugins (/Users/romainlanz/workspace/qualitas-helvetica.ch/node_modules/nodemailer/lib/nodemailer.js:352:16)
    at Nodemailer.<anonymous> (/Users/romainlanz/workspace/qualitas-helvetica.ch/node_modules/nodemailer/lib/nodemailer.js:318:14)
    at Nodemailer._processPlugins (/Users/romainlanz/workspace/qualitas-helvetica.ch/node_modules/nodemailer/lib/nodemailer.js:352:16)
    at Nodemailer.sendMail (/Users/romainlanz/workspace/qualitas-helvetica.ch/node_modules/nodemailer/lib/nodemailer.js:280:10)
    at MailGun.send (/Users/romainlanz/workspace/qualitas-helvetica.ch/node_modules/adonis-mail-provider/src/Mail/Drivers/BaseDriver.js:60:22)
    at Mail.send (/Users/romainlanz/workspace/qualitas-helvetica.ch/node_modules/adonis-mail-provider/src/Mail/Mail.js:129:30)
    at next (native)
    at onFulfilled (/Users/romainlanz/workspace/qualitas-helvetica.ch/node_modules/co/index.js:65:19)
    at process._tickDomainCallback (internal/process/next_tick.js:129:7) nested: undefined, status: 500 }
```
</details>

The error seems to be thrown when we are calling `got.post(...)` on the MailGun API. It's [at the line 75 of the MailGun driver](https://github.com/adonisjs/adonis-mail/blob/develop/src/Mail/Drivers/MailGun/transport.js#L75)

**Comment by indr** [comment]
I'm using `adonis-mail-provider` version `2.0.0` and had the same problem. The package references `got` only as a dev dependency. npm pulled version 3.x because this version is referenced by the package `package-json`.

`npm install --save got` installed 6.x and solved this problem for me.

**Comment by thetutlage** [comment]
@RomainLanz Would you try to install `got` as a your project dependency and let me know if it works. I will add it as a dependency then.

**Comment by RomainLanz** [comment]
I confirm that installing `got` directly in my project does the trick!

**Comment by thetutlage** [comment]
Cool, I will fix it by including it as a dependency.
